name: Docker build, publish and deploy

on:
  push:
    branches:
      - master
      - dev

  workflow_dispatch:
    inputs:
      docker_label:
        description: 'Docker image will be pushed to edulint/edulint-web-frontend:<docker_label>. For deploy to dev server use tag dev.'
        required: true
        default: 'latest'

env:
  docker_label: "${{ inputs.docker_label || github.ref == 'refs/heads/master' && 'latest' || 'dev' }}"
  TARGET_FOLDER: "${{ github.ref == 'refs/heads/master' && secrets.SSH_PROD_FOLDER || secrets.SSH_DEV_FOLDER }}"


jobs:
  docker-build-and-publish-image:
    # https://github.com/marketplace/actions/build-and-push-docker-images
    # We can skip some of the steps.
    runs-on: ubuntu-latest
    steps:
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: edulint/edulint-web-frontend:${{ env.docker_label }}

  deploy:
    needs: docker-build-and-publish-image
    runs-on: ubuntu-latest
    steps:
      - name: Commands over SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host:     ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key:      ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            cd ${{ env.TARGET_FOLDER }}
            docker-compose pull
            docker-compose up -d --build
            echo "Successfully deployed, hooray!"
